### ISSUE TITLE
Allow to define max text field length in watchset definition

### ISSUE THREAD

**Issue by vaspa** [ossw/ossw-firmware-s120#16]
I'd like to know if the String properties could be longer than 32 characters.
Some properties, e.g. music track names often reach 40-50 characters.

**Comment by althink** [comment]
Current limit is 32bytes but it's only android app limit. It can be changed up to 253 bytes, above that you will reach firmware limit. It should be configurable in control definition so we will not waste memory for controls that will show short texts.

**Comment by vaspa** [comment]
A length property (for text control) and corresponding modifications added to the android app
