### ISSUE TITLE
OSSW Weather extension - add Multilingual support

### ISSUE THREAD

**Issue by animavitis** [ossw/ossw-firmware-s120#24]
Hi

OpenWeatherMap offer multilingual support and it would be nice if weather plug had an additional parameter for selecting language :)

API call: http://api.openweathermap.org/data/2.5/forecast/daily?id=524901&lang={lang} 

> You can use lang parameter to get the output in your language. We support the following languages that you can use with the corresponded lang values: English - en, Russian - ru, Italian - it, Spanish - es (or sp), Ukrainian - uk (or ua), German - de, Portuguese - pt, Romanian - ro, Polish - pl, Finnish - fi, Dutch - nl, French - fr, Bulgarian - bg, Swedish - sv (or se), Chinese Traditional - zh_tw, Chinese Simplified - zh (or zh_cn), Turkish - tr, Croatian - hr, Catalan - ca )

**Comment by vaspa** [comment]
I've added a language preference to the weather plugin.
Please remind that currently the OSSW firmware renders only Latin characters.
I hope that accented, Cyrillic, Greek and other characters will be supported soon.
