### ISSUE TITLE
No ringing notification on Goclever Insignia 550i

### ISSUE THREAD

**Issue by aleksandar777** [ossw/ossw-firmware-s120#28]
Hi, i am new here, but i am following this project.
I have Goclever Insignia 550i, and watch does not notify on ringing.
Maybe dual sim capability has something with it.
Viber also not showing, but i do not know if it is implemented yet.

fw 0.4.1, and latest android app

**Comment by zigastegu** [comment]
is this still valid?

**Comment by aleksandar777** [comment]
Solved by latest android version by Pavel
