### ISSUE TITLE
no notifications, no alert notifications

### ISSUE THREAD

**Issue by lcapriotti** [ossw/ossw-firmware-s120#30]
OSSW 0.5beta, Android 0.5beta APK.
Samsung Galaxy Nexus, CM11 (Android 4.4.4).

The smartwatch does not react to the "test notifications" and "test alert notifications" entries, on the phone the notifications are created in the notification bar, though.

**Comment by zigastegu** [comment]
is this still valid?

**Comment by lcapriotti** [comment]
I managed to get notifications and alert notifications yesterday by modifying the active time interval as you advised, but I still think there is something to be checked as this morning I had to do it again because they were not working again. Like the time interval was lost despite it was shown correctly.
