### ISSUE TITLE
Improve buttons response time and eliminate fake long presses

### ISSUE THREAD

**Issue by althink** [ossw/ossw-firmware-s120#8]

**Comment by vaspa** [comment]
I also noticed several false long presses while testing the buttons in the settings menu. Is it handled with the 250ms delay defined in the buttons.h header file?
I think that 500-700ms will be more appropriate.

**Comment by althink** [comment]
Changing this delay parameter won't help and even decrease user experience (because short press event will be also triggered after 500-700ms). I have to rewrite this part because it was written quick and dirty way.

**Comment by althink** [comment]
Looks like it will stay quick and dirty but this time it will work like it should from the beginning ;)
